"""empty message

Revision ID: 00327bfa813d
Revises: 57ff0479bc36
Create Date: 2020-07-09 21:59:47.894163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00327bfa813d'
down_revision = '57ff0479bc36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todo', 'descriptio',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todo', 'descriptio',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
