"""empty message

Revision ID: 57ff0479bc36
Revises: 5e5b78450dde
Create Date: 2020-07-09 21:49:23.414103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57ff0479bc36'
down_revision = '5e5b78450dde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('descriptio', sa.String(), nullable=True))
    op.execute("update todo set descriptio = 'test' where descriptio is null;")
    op.alter_column('todo', 'completed', nullable=True)
    op.drop_column('todo', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('todo', 'descriptio')
    # ### end Alembic commands ###
