"""empty message

Revision ID: 5e5b78450dde
Revises: 8b34faee9eef
Create Date: 2020-07-09 21:39:53.241358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e5b78450dde'
down_revision = '8b34faee9eef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('completed', sa.Boolean(), nullable=False))
    op.add_column('todo', sa.Column('description', sa.String(), nullable=False))
    op.drop_column('todo', 'descriptio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('descriptio', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('todo', 'description')
    op.drop_column('todo', 'completed')
    # ### end Alembic commands ###
