"""empty message

Revision ID: 628f02c4b7c7
Revises: 00327bfa813d
Create Date: 2020-07-09 22:17:03.341370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '628f02c4b7c7'
down_revision = '00327bfa813d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('todo', 'descriptio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('descriptio', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('todo', 'description')
    # ### end Alembic commands ###
