"""empty message

Revision ID: 8b34faee9eef
Revises: 
Create Date: 2020-07-09 21:33:59.815984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b34faee9eef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('descriptio', sa.String(), nullable=False))
    op.drop_column('todo', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('todo', 'descriptio')
    # ### end Alembic commands ###
